trabajador_index:
    path:     /
    defaults: { _controller: "scsBundle:Trabajador:index" }
    methods:  GET

trabajador_show:
    path:     /{id}/show
    defaults: { _controller: "scsBundle:Trabajador:show" }
    methods:  GET

trabajador_new:
    path:     /new
    defaults: { _controller: "scsBundle:Trabajador:new" }
    methods:  [GET, POST]

trabajador_edit:
    path:     /{id}/edit
    defaults: { _controller: "scsBundle:Trabajador:edit" }
    methods:  [GET, POST]

trabajador_delete:
    path:     /{id}/delete
    defaults: { _controller: "scsBundle:Trabajador:delete" }
