<?php

namespace scsBundle\Repository;

/**
 * BaseCalculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseCalculoRepository extends \Doctrine\ORM\EntityRepository
{
}
