<?php

namespace scsBundle\Repository;
use scsBundle\Entity\Coeficiente;

/**
 * CoeficienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoeficienteRepository extends \Doctrine\ORM\EntityRepository
{

    public function findBydate(Coeficiente $coeficiente)    {
        $qb = $this->createQueryBuilder('c');

        return $qb->where('c.mes = :mes AND c.mes = :ano')
            ->setParameter('mes', $coeficiente->getMes)
            ->setParameter('ano', $coeficiente->getAno)
            ->getQuery()
            ->getOneOrNullResult();
            ;
    }
}
