<?php

namespace scsBundle\Repository;

/**
 * EscalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscalaRepository extends \Doctrine\ORM\EntityRepository
{
}
