<?php

namespace scsBundle\Repository;

/**
 * PrenominaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrenominaRepository extends \Doctrine\ORM\EntityRepository
{
}
