<?php

namespace scsBundle\Repository;

/**
 * TallerProduccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TallerProduccionRepository extends \Doctrine\ORM\EntityRepository
{
}
