<?php

namespace scsBundle\Repository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
    /**
     * Loads the user for the given username.
     *
     * This method must return null if the user is not found.
     *
     * @param string $username The username
     *
     * @return UserInterface|null
     */
    public function loadUserByUsername($username)
    {
        $user = $this->createQueryBuilder('u')
            ->where('u.usuario = :usuario')
            ->setParameter('usuario', $username)
            ->getQuery()
            ->getOneOrNullResult();
        if (null === $user) {
            $message = sprintf(
                'El usuario "%s" no existe en el sistema.',
                $username
            );
            throw new UsernameNotFoundException($message);
        }
        return $user;
    }
}
